### PR TITLE
add npm installation instructions

### PR DESCRIPTION
**Pull request by jasonkarns**

### CODE REVIEW

**Comment by ztombol** [comment]
Notes should start with the capital "N" and be in italics. See the Loading section for an [example](https://github.com/ztombol/bats-docs/blob/master/README.md#loading).

**Comment by jasonkarns** [comment]
Except npm should never be capitalized. Reword so npm isn't the first word?

**Comment by ztombol** [comment]
I meant the _"n"_ in _"note: ..."_, [here](https://github.com/ztombol/bats-docs/pull/5/files#diff-04c6e90faac2675aa89e2176d2eec7d8R41) and [here](https://github.com/ztombol/bats-docs/pull/5/files#diff-04c6e90faac2675aa89e2176d2eec7d8R55).

Make it look like this:

**_Note:**_ _Important note._

With this:

```
***Note:*** *Important note.*
```

Otherwise it's good!

**Comment by jasonkarns** [comment]
ah! haha. roger :)

**Comment by jasonkarns** [comment]
updated, though I changed the markdown style of the note to use `__` for the bold, to distinguish from the italics.

```
*__Note:__ Stuff*
```

slightly more clear in markdown, IMO. but i can switch back if desired. (and compared on babelmark, both forms are consistent across markdown implementations, so no difference in support either way)

**Comment by ztombol** [comment]
Looks good to me.
The new markdown style looks better. Thanks for that too!
Merging. :)

**Pull request merged**
