### PR TITLE
add install instruction for brew.

### PR DESCRIPTION
**Pull request by kaos**
cross ref #1

### CODE REVIEW

**Comment by ztombol** [comment]
I apologize for the delay. I always try to reply within 24 hours, but a lot has been on my plate in the past two weeks. I've got to tell you I've been anxiously waiting to review your patch. Homebrew support would be awesome!

It could be another day or two before I can get back to you. Just wanted to give a heads up and let you know that your contribution is very welcome, and I definitely haven't forgotten it. Thanks for the patience. :bow:

**Comment by kaos** [comment]
Cudos for the feedback, and no worries, I know how it is when there's more you want to do, than can fit into the time you've got. :)

**Comment by ztombol** [comment]
I don't have access to an OSX box, but I trust you that it works. :)

On the documentation I have a few suggestions. Some of which seem like nitpicking. I haven't slept much. I apologise in advance. Feel free to reject any of them. :smile: 
- We should point out that, in contrast to other installation methods, `homebrew` installs system-wide. Simply including the word _system-wide_ somewhere should suffice. For example, as in _"OS X users can use Homebrew to install libraries system-wide."_
- The note on automatically installing `bats-support` and `bats` should explicitly mention that it's done so because they are **dependencies**. This may not be readily apparent to newcomers.
- You have a typo in _vari**uo**s_.
- Spell out _utils_ instead of abbreviating. Looks better in my opinion.
- Add an example to the _Loading_ section. Just below the `npm` example is fine. If _HOMEBREW_PREFIX_ can be detected in the environment, the example should use that. I'm not actually sure if this is how Homebrew  @works. If not, the default is okay.

Homebrew support is great! Thanks a lot again!

---

_I appologise for the massive delay. I'm not promising that it won't happen again, but I'll do my best to be more responsive. Hopefully I can return to my normal <24 hours delays soon. Thanks for the patience again._ :bow:

**Comment by kaos** [comment]
Rebased and squashed a new commit, addressing your comments.
Didn't get your reference to where I had abbreviated _utils_, though.

When installing (as well as on info output, as shown below), there's a notice message describing how to load the libs, as a nice complement to the docs... ;)

```
$ brew info bats-assert
kaos/shell/bats-assert: stable 0.3.0, HEAD
Common assertions for Bats
https://github.com/ztombol/bats-assert
/usr/local/Cellar/bats-assert/HEAD (16 files, 82.8K) *
  Built from source
From: https://github.com/kaos/homebrew-shell/blob/master/Formula/bats-assert.rb
==> Dependencies
Required: bats-support ✔
==> Caveats

To load the bats-assert lib in your bats test:

    load '/usr/local/lib/bats-support/load.bash'
    load '/usr/local/lib/bats-assert/load.bash'

$
```

Don't worry about nit-picking, I'm one myself too.. 😃 though, my native tongue is not English, so I do miss the occasional grammar or spelling.. 😝 

There's also a way to run the test suite for the lib, using `brew test bats-assert` for instance. I left it out of the docs for the time being, as it didn't work for me just now (it did work last time I was at it, so not sure what's changed..)

**Comment by ztombol** [comment]
#### Spelling

I meant spelling out _utilties_ instead of abbreviating it as _utils_.

> The forumlae are in a tap for various shell **utils** by [@kaos](https://github.com/kaos), so enable the tap [kaos/shell](https://github.com/kaos/homebrew-shell) first.

#### Loading

In the _Loading_ section, I think you are missing a `/lib` in the parenthesis.

> For brew installations, load the libraries from $(brew --prefix)/lib/ (which is /usr/local**/lib** by default):

The example should use `$(brew --prefix)` instead of hard-coding the default to be generally useful.

``` sh
TEST_BREW_PREFIX="$(brew --prefix)"
load "${TEST_BREW_PREFIX}/lib/bats-support/load.bash"
load "${TEST_BREW_PREFIX}/lib/bats-assert/load.bash"
```

Storing the prefix in a variable avoids invoking an extra subshell every time.

It was a good idea to add a note on `load` only appending `.bash` when the given path is relative.

#### Testing

Thanks for mentioning testing! We don't need to add `brew test bats-assert` for now. The other installation methods don't mention testing either.

Since the beginning I've intended this repo to be a specification for bats helpers. But didn't want to say that explicitely before adding exact constraints on behaviour (e.g. loading has no side-effects, directory structure) and guidelines (as well as a skeleton) for writing new libraries.

Don't sweat the spelling mistakes! I'm not a native speaker of English myself. :smile:

Thanks!

**Comment by kaos** [comment]
Right, will spell out _utilities_. So used to _utils_ that I didn't even consider it a abbreviation.

I were considering the options there.. and opted for brevity, with a hint of how to find out the current value, also as the output when installing, as well as on `brew info` you'll get correct values. But, it's an easy fix, will do ;)

Regarding missing `/lib` in the parenthesis, I was referring to the default for `brew --prefix` which is `/usr/local`.. perhaps I should make that clearer).

**Comment by ztombol** [comment]
I understand. I considered the same when writing the _Installation_ section for `git`. I think, the portable version would demonstrate a better practice than hardcoding the values.

> ... `$(brew --prefix)/lib/` (which is `/usr/local` by default):

To me _"which"_ refers to `$(brew --prefix)/lib/`, which in turn is `/usr/local/lib`. But it's easy to understand what you meant, so I think I'm just being too pedantic.. :smile:

I leave it up to you. :)

**Comment by kaos** [comment]
Ok, I've addressed your last comments, and pushed an amended commit to keep the changes in a single commit.

**Comment by ztombol** [comment]
@kaos Looking good! Merging, finally... Sorry, I put this off for way too long. This is an important addition! Thank you very much for your hard work. And thanks again for the patience. :bow:

**Comment by kaos** [comment]
Thanks :)

lör 21 maj 2016 kl. 14:04 skrev Zoltán Tömböl notifications@github.com:

**Pull request merged**
